language: node_js
node_js:
  - "node"
  - "lts/*"

script:
  - npm run travis:test
  - npm run lint

after_success:
  - npm run travis:coverage
  - npm run build:examples
  - sed -i '' '/\/examples/d' .gitignore # allow examples js to be committed

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    node_js: node
