language: node_js
node_js:
  - "node"
  - "lts/*"

script:
  - npm run travis:test
  - npm run lint

after_success:
  - npm run travis:coverage
  - npm run build:examples
  - touch .nojekyll # See https://github.com/zeit/next.js/wiki/Deploying-a-Next.js-app-into-GitHub-Pages#add-a-nojekyll-file

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
